import { SchemaDefinition, ScalarFieldTypeEnum } from "lucid-extension-sdk";

export const EntityThroughputCrossRepSummarySchema: SchemaDefinition = {
    fields: [
        { name: "id", type: ScalarFieldTypeEnum.STRING }, 
        { name: "scenario_id", type: ScalarFieldTypeEnum.STRING },
        { name: "scenario_name", type: ScalarFieldTypeEnum.STRING },
        { name: "entity_id", type: ScalarFieldTypeEnum.STRING },
        { name: "entity_name", type: ScalarFieldTypeEnum.STRING },
        { name: "count_mean", type: ScalarFieldTypeEnum.NUMBER },
        { name: "count_median", type: ScalarFieldTypeEnum.NUMBER },
        { name: "count_std_dev", type: ScalarFieldTypeEnum.NUMBER },
        { name: "completed_count_mean", type: ScalarFieldTypeEnum.NUMBER },
        { name: "completed_count_median", type: ScalarFieldTypeEnum.NUMBER },
        { name: "completed_count_std_dev", type: ScalarFieldTypeEnum.NUMBER },
        { name: "in_progress_count_mean", type: ScalarFieldTypeEnum.NUMBER },
        { name: "in_progress_count_median", type: ScalarFieldTypeEnum.NUMBER },
        { name: "in_progress_count_std_dev", type: ScalarFieldTypeEnum.NUMBER },
        { name: "throughput_rate_mean", type: ScalarFieldTypeEnum.NUMBER },
        { name: "throughput_rate_median", type: ScalarFieldTypeEnum.NUMBER },
        { name: "throughput_rate_std_dev", type: ScalarFieldTypeEnum.NUMBER },
        { name: "throughput_rate_cv", type: ScalarFieldTypeEnum.NUMBER },
        { name: "interval_mean", type: ScalarFieldTypeEnum.NUMBER },
        { name: "interval_median", type: ScalarFieldTypeEnum.NUMBER },
        { name: "interval_std_dev", type: ScalarFieldTypeEnum.NUMBER },
        { name: "interval_cv", type: ScalarFieldTypeEnum.NUMBER },
        { name: "first_exit_mean", type: ScalarFieldTypeEnum.NUMBER },
        { name: "first_exit_median", type: ScalarFieldTypeEnum.NUMBER },
        { name: "first_exit_std_dev", type: ScalarFieldTypeEnum.NUMBER },
        { name: "last_exit_mean", type: ScalarFieldTypeEnum.NUMBER },
        { name: "last_exit_median", type: ScalarFieldTypeEnum.NUMBER },
        { name: "last_exit_std_dev", type: ScalarFieldTypeEnum.NUMBER },
    ],
    primaryKey: ["id"],
    fieldLabels: {
        'id': 'ID',
        'scenario_id': 'Scenario Id',
        'scenario_name': 'Scenario Name',
        'entity_id': 'Entity Id',
        'entity_name': 'Entity Name',
        'count_mean': 'Count Mean',
        'count_median': 'Count Median',
        'count_std_dev': 'Count Std Dev',
        'completed_count_mean': 'Completed Count Mean',
        'completed_count_median': 'Completed Count Median',
        'completed_count_std_dev': 'Completed Count Std Dev',
        'in_progress_count_mean': 'In Progress Count Mean',
        'in_progress_count_median': 'In Progress Count Median',
        'in_progress_count_std_dev': 'In Progress Count Std Dev',
        'throughput_rate_mean': 'Throughput Rate Mean',
        'throughput_rate_median': 'Throughput Rate Median',
        'throughput_rate_std_dev': 'Throughput Rate Std Dev',
        'throughput_rate_cv': 'Throughput Rate CV',
        'interval_mean': 'Interval Mean',
        'interval_median': 'Interval Median',
        'interval_std_dev': 'Interval Std Dev',
        'interval_cv': 'Interval CV',
        'first_exit_mean': 'First Exit Mean',
        'first_exit_median': 'First Exit Median',
        'first_exit_std_dev': 'First Exit Std Dev',
        'last_exit_mean': 'Last Exit Mean',
        'last_exit_median': 'Last Exit Median',
        'last_exit_std_dev': 'Last Exit Std Dev'
    }
};