// schemas/resourceRepSummary.ts
import { SchemaDefinition, ScalarFieldTypeEnum } from "lucid-extension-sdk";

export const ResourceRepSummarySchema: SchemaDefinition = {
    fields: [
        { name: "id", type: ScalarFieldTypeEnum.STRING },
        { name: "scenario_id", type: ScalarFieldTypeEnum.STRING },
        { name: "scenario_name", type: ScalarFieldTypeEnum.STRING },
        { name: "resource_id", type: ScalarFieldTypeEnum.STRING },
        { name: "resource_name", type: ScalarFieldTypeEnum.STRING },
        { name: "rep", type: ScalarFieldTypeEnum.NUMBER },
        { name: "capacity", type: ScalarFieldTypeEnum.NUMBER },
        { name: "total_available_clock", type: ScalarFieldTypeEnum.NUMBER },
        { name: "total_requests", type: ScalarFieldTypeEnum.NUMBER },
        { name: "successful_requests", type: ScalarFieldTypeEnum.NUMBER },
        { name: "failed_requests", type: ScalarFieldTypeEnum.NUMBER },
        { name: "times_acquired", type: ScalarFieldTypeEnum.NUMBER },
        { name: "times_released", type: ScalarFieldTypeEnum.NUMBER },
        { name: "total_time_in_use", type: ScalarFieldTypeEnum.NUMBER },
        { name: "total_time_idle", type: ScalarFieldTypeEnum.NUMBER },
        { name: "total_blocking_time", type: ScalarFieldTypeEnum.NUMBER },
        { name: "average_utilization", type: ScalarFieldTypeEnum.NUMBER },
        { name: "peak_utilization", type: ScalarFieldTypeEnum.NUMBER },
        { name: "current_utilization", type: ScalarFieldTypeEnum.NUMBER },
        { name: "average_wait_time", type: ScalarFieldTypeEnum.NUMBER },
        { name: "max_wait_time", type: ScalarFieldTypeEnum.NUMBER },
        { name: "average_queue_length", type: ScalarFieldTypeEnum.NUMBER },
        { name: "max_queue_length", type: ScalarFieldTypeEnum.NUMBER },
        { name: "total_conflicts", type: ScalarFieldTypeEnum.NUMBER },
        { name: "conflict_frequency", type: ScalarFieldTypeEnum.NUMBER }
    ],
    primaryKey: ["id"],
    fieldLabels: {
        'id': 'ID',
        'scenario_id': 'Scenario Id',
        'scenario_name': 'Scenario Name',
        'resource_id': 'Resource ID',
        'resource_name': 'Resource Name',
        'rep': 'Replication',
        'capacity': 'Capacity',
        'total_available_clock': 'Total Available Clock',
        'total_requests': 'Total Requests',
        'successful_requests': 'Successful Requests',
        'failed_requests': 'Failed Requests',
        'times_acquired': 'Times Acquired',
        'times_released': 'Times Released',
        'total_time_in_use': 'Total Time In Use',
        'total_time_idle': 'Total Time Idle',
        'total_blocking_time': 'Total Blocking Time',
        'average_utilization': 'Average Utilization',
        'peak_utilization': 'Peak Utilization',
        'current_utilization': 'Current Utilization',
        'average_wait_time': 'Average Wait Time',
        'max_wait_time': 'Max Wait Time',
        'average_queue_length': 'Average Queue Length',
        'max_queue_length': 'Max Queue Length',
        'total_conflicts': 'Total Conflicts',
        'conflict_frequency': 'Conflict Frequency'
    }
};