/**
 * Message type constants for the Quodsi postMessage protocol.
 * These constants serve as discriminators for the message payload schemas.
 */
export enum EnvelopeMessageType {
  // Framework & Lifecycle
  REACT_APP_READY = "REACT_APP_READY",
  ERROR = "ERROR",
  LOG = "LOG",
  
  // Authentication
  AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS",
  AUTH_LOGOUT = "AUTH_LOGOUT",
  AUTH_STATUS = "AUTH_STATUS",
  AUTH_REQUIRED = "AUTH_REQUIRED",
  AUTH_ERROR = "AUTH_ERROR",
  
  // Selection & Context
  MODEL_CONTEXT = "MODEL_CONTEXT",
  SELECTION_CHANGED = "SELECTION_CHANGED",
  
  // Simulation Run
  MODEL_RUN_REQUEST = "MODEL_RUN_REQUEST",
  MODEL_RUN_STATUS = "MODEL_RUN_STATUS",  // Now includes initial acknowledgment (queuedAt field)
  
  // Model Operations
  MODEL_VALIDATE = "MODEL_VALIDATE",
  MODEL_VALIDATION_RESULT = "MODEL_VALIDATION_RESULT",
  MODEL_CONVERT = "MODEL_CONVERT",
  MODEL_CONVERSION_RESULT = "MODEL_CONVERSION_RESULT",

  // Conversion Preview
  CONVERSION_PREVIEW_REQUEST = "CONVERSION_PREVIEW_REQUEST",
  CONVERSION_PREVIEW_RESULT = "CONVERSION_PREVIEW_RESULT",
  CONVERSION_APPLY = "CONVERSION_APPLY",
  CONVERSION_APPLY_RESULT = "CONVERSION_APPLY_RESULT",
  MODEL_REMOVE = "MODEL_REMOVE",
  MODEL_REMOVE_RESULT = "MODEL_REMOVE_RESULT",
  MODEL_JSON_REQUEST = "MODEL_JSON_REQUEST",
  MODEL_JSON_RESPONSE = "MODEL_JSON_RESPONSE",

  // Element Operations
  ELEMENT_SELECT = "ELEMENT_SELECT",
  ELEMENT_UPDATE = "ELEMENT_UPDATE",
  ELEMENT_UPDATE_RESULT = "ELEMENT_UPDATE_RESULT",
  ELEMENT_CONVERT = "ELEMENT_CONVERT",
  ELEMENT_CONVERT_RESULT = "ELEMENT_CONVERT_RESULT",
  STATES_UPDATE = "STATES_UPDATE",
  STATES_UPDATE_RESULT = "STATES_UPDATE_RESULT",
  RESOURCE_REQUIREMENTS_UPDATE = "RESOURCE_REQUIREMENTS_UPDATE",
  RESOURCE_REQUIREMENTS_UPDATE_RESULT = "RESOURCE_REQUIREMENTS_UPDATE_RESULT",
  TIME_PATTERNS_UPDATE = "TIME_PATTERNS_UPDATE",
  TIME_PATTERNS_UPDATE_RESULT = "TIME_PATTERNS_UPDATE_RESULT",
  TIME_DISTRIBUTED_CONFIGS_UPDATE = "TIME_DISTRIBUTED_CONFIGS_UPDATE",
  TIME_DISTRIBUTED_CONFIGS_UPDATE_RESULT = "TIME_DISTRIBUTED_CONFIGS_UPDATE_RESULT",

  // Cloud Storage
  STORAGE_CONNECT_REQUEST = "STORAGE_CONNECT_REQUEST",
  STORAGE_CONNECT_RESULT = "STORAGE_CONNECT_RESULT",
  STORAGE_DISCONNECT = "STORAGE_DISCONNECT",
  STORAGE_STATUS = "STORAGE_STATUS",

  // Simulation Run Management
  SIMULATION_RUNS_LIST_REQUEST = "SIMULATION_RUNS_LIST_REQUEST",
  SIMULATION_RUNS_LIST_RESULT = "SIMULATION_RUNS_LIST_RESULT",
  SIMULATION_RUN_DELETE = "SIMULATION_RUN_DELETE",
  SIMULATION_RUN_DELETE_RESULT = "SIMULATION_RUN_DELETE_RESULT",
  SIMULATION_RUN_RESIMULATE_REQUEST = "SIMULATION_RUN_RESIMULATE_REQUEST",
  SIMULATION_RUN_CANCEL_REQUEST = "SIMULATION_RUN_CANCEL_REQUEST",
  SIMULATION_RUN_CANCEL_RESULT = "SIMULATION_RUN_CANCEL_RESULT",
  CROSS_REP_DATA_REQUEST = "CROSS_REP_DATA_REQUEST",
  CROSS_REP_DATA_RESULT = "CROSS_REP_DATA_RESULT",
  CROSS_REP_BATCH_DATA_REQUEST = "CROSS_REP_BATCH_DATA_REQUEST",
  CROSS_REP_BATCH_DATA_RESULT = "CROSS_REP_BATCH_DATA_RESULT",

  // Scenario Definition Management (shapeData)
  SCENARIOS_DEFINITION_UPDATE = "SCENARIOS_DEFINITION_UPDATE",
  SCENARIOS_DEFINITION_RESULT = "SCENARIOS_DEFINITION_RESULT",
  SCENARIOS_LIST_REQUEST = "SCENARIOS_LIST_REQUEST",
  SCENARIOS_LIST_RESULT = "SCENARIOS_LIST_RESULT",

  // Sync All (model + scenarios + runs)
  SYNC_ALL_REQUEST = "SYNC_ALL_REQUEST",
  SYNC_ALL_SUCCESS = "SYNC_ALL_SUCCESS",
  SYNC_ALL_ERROR = "SYNC_ALL_ERROR",

  // Modal
  OPEN_RESULTS_MODAL = "OPEN_RESULTS_MODAL",

  // Studio Embed Token Relay
  REQUEST_STUDIO_TOKEN = "REQUEST_STUDIO_TOKEN",
  STUDIO_TOKEN = "STUDIO_TOKEN",

  // DevTools
  DEVTOOLS_SWIMLANE_SCAN_REQUEST = "DEVTOOLS_SWIMLANE_SCAN_REQUEST",
  DEVTOOLS_SWIMLANE_SCAN_RESULT = "DEVTOOLS_SWIMLANE_SCAN_RESULT",
  DEVTOOLS_KINDE_AUTH_REQUEST = "DEVTOOLS_KINDE_AUTH_REQUEST",
  DEVTOOLS_KINDE_AUTH_RESULT = "DEVTOOLS_KINDE_AUTH_RESULT",

  // Swimlane Operations
  SWIMLANE_UPDATE = "SWIMLANE_UPDATE",
  SWIMLANE_UPDATE_RESULT = "SWIMLANE_UPDATE_RESULT",
  SWIMLANE_CONVERT_LANE = "SWIMLANE_CONVERT_LANE",
  SWIMLANE_CONVERT_LANE_RESULT = "SWIMLANE_CONVERT_LANE_RESULT",

  // Billing & Entitlements (Kinde)
  ENTITLEMENTS_STATUS = "ENTITLEMENTS_STATUS",
  PORTAL_URL_REQUEST = "PORTAL_URL_REQUEST",
  PORTAL_URL_RESPONSE = "PORTAL_URL_RESPONSE",

  // Analytics
  ANALYTICS_TRACK = "ANALYTICS_TRACK"
}
