/**
 * Message type constants for the Quodsi postMessage protocol.
 * These constants serve as discriminators for the message payload schemas.
 */
export enum EnvelopeMessageType {
  // Framework & Lifecycle
  REACT_APP_READY = "REACT_APP_READY",
  ERROR = "ERROR",
  LOG = "LOG",
  
  // Authentication
  AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS",
  AUTH_LOGOUT = "AUTH_LOGOUT",
  AUTH_PASSWORD_RESET = "AUTH_PASSWORD_RESET",
  AUTH_STATUS = "AUTH_STATUS",
  AUTH_REQUIRED = "AUTH_REQUIRED",
  AUTH_ERROR = "AUTH_ERROR",
  REQUEST_AUTH_STATUS = "REQUEST_AUTH_STATUS",
  
  // Subscription & Billing
  SUBSCRIPTION_STATUS = "SUBSCRIPTION_STATUS",
  SUBSCRIPTION_CHANGE_REQUEST = "SUBSCRIPTION_CHANGE_REQUEST",
  SUBSCRIPTION_CHANGE_RESULT = "SUBSCRIPTION_CHANGE_RESULT",
  SUBSCRIPTION_ERROR = "SUBSCRIPTION_ERROR",
  
  // Selection & Context
  MODEL_CONTEXT = "MODEL_CONTEXT",
  SELECTION_CHANGED = "SELECTION_CHANGED",
  
  // Simulation Run
  MODEL_RUN_REQUEST = "MODEL_RUN_REQUEST",
  MODEL_RUN_STATUS = "MODEL_RUN_STATUS",  // Now includes initial acknowledgment (queuedAt field)
  
  // Model Operations
  MODEL_VALIDATE = "MODEL_VALIDATE",
  MODEL_VALIDATION_RESULT = "MODEL_VALIDATION_RESULT",
  MODEL_CONVERT = "MODEL_CONVERT",
  MODEL_CONVERSION_RESULT = "MODEL_CONVERSION_RESULT",

  // Conversion Preview
  CONVERSION_PREVIEW_REQUEST = "CONVERSION_PREVIEW_REQUEST",
  CONVERSION_PREVIEW_RESULT = "CONVERSION_PREVIEW_RESULT",
  CONVERSION_APPLY = "CONVERSION_APPLY",
  CONVERSION_APPLY_RESULT = "CONVERSION_APPLY_RESULT",
  MODEL_REMOVE = "MODEL_REMOVE",
  MODEL_REMOVE_RESULT = "MODEL_REMOVE_RESULT",
  MODEL_JSON_REQUEST = "MODEL_JSON_REQUEST",
  MODEL_JSON_RESPONSE = "MODEL_JSON_RESPONSE",
  RESULTS_PAGE_CREATE = "RESULTS_PAGE_CREATE",
  RESULTS_PAGE_CREATE_RESULT = "RESULTS_PAGE_CREATE_RESULT",
  
  // Element Operations
  ELEMENT_UPDATE = "ELEMENT_UPDATE",
  ELEMENT_UPDATE_RESULT = "ELEMENT_UPDATE_RESULT",
  ELEMENT_CONVERT = "ELEMENT_CONVERT",
  ELEMENT_CONVERT_RESULT = "ELEMENT_CONVERT_RESULT",
  STATES_UPDATE = "STATES_UPDATE",
  STATES_UPDATE_RESULT = "STATES_UPDATE_RESULT",
  RESOURCE_REQUIREMENTS_UPDATE = "RESOURCE_REQUIREMENTS_UPDATE",
  RESOURCE_REQUIREMENTS_UPDATE_RESULT = "RESOURCE_REQUIREMENTS_UPDATE_RESULT",
  TIME_PATTERNS_UPDATE = "TIME_PATTERNS_UPDATE",
  TIME_PATTERNS_UPDATE_RESULT = "TIME_PATTERNS_UPDATE_RESULT",
  TIME_DISTRIBUTED_CONFIGS_UPDATE = "TIME_DISTRIBUTED_CONFIGS_UPDATE",
  TIME_DISTRIBUTED_CONFIGS_UPDATE_RESULT = "TIME_DISTRIBUTED_CONFIGS_UPDATE_RESULT",

  // Cloud Storage
  STORAGE_CONNECT_REQUEST = "STORAGE_CONNECT_REQUEST",
  STORAGE_CONNECT_RESULT = "STORAGE_CONNECT_RESULT",
  STORAGE_DISCONNECT = "STORAGE_DISCONNECT",
  STORAGE_STATUS = "STORAGE_STATUS",

  // Scenario Management
  SCENARIOS_LIST_REQUEST = "SCENARIOS_LIST_REQUEST",
  SCENARIOS_LIST_RESULT = "SCENARIOS_LIST_RESULT",
  SCENARIO_DELETE = "SCENARIO_DELETE",
  SCENARIO_DELETE_RESULT = "SCENARIO_DELETE_RESULT",
  SCENARIO_RESIMULATE_REQUEST = "SCENARIO_RESIMULATE_REQUEST",
  CROSS_REP_DATA_REQUEST = "CROSS_REP_DATA_REQUEST",
  CROSS_REP_DATA_RESULT = "CROSS_REP_DATA_RESULT"
}
