/**
 * Message type constants for the Quodsi postMessage protocol.
 * These constants serve as discriminators for the message payload schemas.
 */
export enum EnvelopeMessageType {
  // Framework & Lifecycle
  REACT_APP_READY = "REACT_APP_READY",
  ERROR = "ERROR",
  LOG = "LOG",
  
  // Authentication
  AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS",
  AUTH_LOGOUT = "AUTH_LOGOUT",
  AUTH_STATUS = "AUTH_STATUS",
  AUTH_REQUIRED = "AUTH_REQUIRED",
  AUTH_ERROR = "AUTH_ERROR",
  
  // Selection & Context
  MODEL_CONTEXT = "MODEL_CONTEXT",
  SELECTION_CHANGED = "SELECTION_CHANGED",
  
  // Simulation Run
  MODEL_RUN_REQUEST = "MODEL_RUN_REQUEST",
  MODEL_RUN_STATUS = "MODEL_RUN_STATUS",  // Now includes initial acknowledgment (queuedAt field)
  
  // Model Operations
  MODEL_VALIDATE = "MODEL_VALIDATE",
  MODEL_VALIDATION_RESULT = "MODEL_VALIDATION_RESULT",
  MODEL_CONVERT = "MODEL_CONVERT",
  MODEL_CONVERSION_RESULT = "MODEL_CONVERSION_RESULT",

  // Conversion Preview
  CONVERSION_PREVIEW_REQUEST = "CONVERSION_PREVIEW_REQUEST",
  CONVERSION_PREVIEW_RESULT = "CONVERSION_PREVIEW_RESULT",
  CONVERSION_APPLY = "CONVERSION_APPLY",
  CONVERSION_APPLY_RESULT = "CONVERSION_APPLY_RESULT",
  MODEL_REMOVE = "MODEL_REMOVE",
  MODEL_REMOVE_RESULT = "MODEL_REMOVE_RESULT",
  MODEL_JSON_REQUEST = "MODEL_JSON_REQUEST",
  MODEL_JSON_RESPONSE = "MODEL_JSON_RESPONSE",

  // Element Operations
  ELEMENT_SELECT = "ELEMENT_SELECT",
  ELEMENT_UPDATE = "ELEMENT_UPDATE",
  ELEMENT_UPDATE_RESULT = "ELEMENT_UPDATE_RESULT",
  ELEMENT_CONVERT = "ELEMENT_CONVERT",
  ELEMENT_CONVERT_RESULT = "ELEMENT_CONVERT_RESULT",
  STATES_UPDATE = "STATES_UPDATE",
  STATES_UPDATE_RESULT = "STATES_UPDATE_RESULT",
  ENTITIES_UPDATE = "ENTITIES_UPDATE",
  ENTITIES_UPDATE_RESULT = "ENTITIES_UPDATE_RESULT",
  RESOURCE_REQUIREMENTS_UPDATE = "RESOURCE_REQUIREMENTS_UPDATE",
  RESOURCE_REQUIREMENTS_UPDATE_RESULT = "RESOURCE_REQUIREMENTS_UPDATE_RESULT",
  TIME_PATTERNS_UPDATE = "TIME_PATTERNS_UPDATE",
  TIME_PATTERNS_UPDATE_RESULT = "TIME_PATTERNS_UPDATE_RESULT",
  TIME_DISTRIBUTED_CONFIGS_UPDATE = "TIME_DISTRIBUTED_CONFIGS_UPDATE",
  TIME_DISTRIBUTED_CONFIGS_UPDATE_RESULT = "TIME_DISTRIBUTED_CONFIGS_UPDATE_RESULT",

  // Cloud Storage
  STORAGE_CONNECT_REQUEST = "STORAGE_CONNECT_REQUEST",
  STORAGE_CONNECT_RESULT = "STORAGE_CONNECT_RESULT",
  STORAGE_DISCONNECT = "STORAGE_DISCONNECT",
  STORAGE_STATUS = "STORAGE_STATUS",

  // Simulation Run Management
  SIMULATION_RUNS_LIST_REQUEST = "SIMULATION_RUNS_LIST_REQUEST",
  SIMULATION_RUNS_LIST_RESULT = "SIMULATION_RUNS_LIST_RESULT",
  SIMULATION_RUN_DELETE = "SIMULATION_RUN_DELETE",
  SIMULATION_RUN_DELETE_RESULT = "SIMULATION_RUN_DELETE_RESULT",
  SIMULATION_RUN_RESIMULATE_REQUEST = "SIMULATION_RUN_RESIMULATE_REQUEST",
  SIMULATION_RUN_CANCEL_REQUEST = "SIMULATION_RUN_CANCEL_REQUEST",
  SIMULATION_RUN_CANCEL_RESULT = "SIMULATION_RUN_CANCEL_RESULT",

  // Modal
  OPEN_ANIMATION_MODAL = "OPEN_ANIMATION_MODAL",
  // Sent by a chromeless embed modal's own "Close" button to ask the host to
  // hide the modal (chromeless modals have no native title-bar X).
  CLOSE_MODAL = "CLOSE_MODAL",

  // Studio Embed Token Relay
  REQUEST_STUDIO_TOKEN = "REQUEST_STUDIO_TOKEN",
  STUDIO_TOKEN = "STUDIO_TOKEN",

  // Studio Embed deferred-path relay. The modal opens INSTANTLY in a "pending"
  // state (before the server model id is resolved); the embed view PULLS the
  // resolved studioPath (REQUEST → reply) once its channel is registered — pull,
  // not push, to avoid the channel-registration race that drops pushed messages.
  REQUEST_STUDIO_EMBED_PATH = "REQUEST_STUDIO_EMBED_PATH",
  STUDIO_EMBED_PATH = "STUDIO_EMBED_PATH",

  // Embedded scenarios editor (Phase 2)
  OPEN_SCENARIOS_MODAL = "OPEN_SCENARIOS_MODAL",
  OPEN_STUDIES_MODAL = "OPEN_STUDIES_MODAL",
  REQUEST_STUDIO_CATALOG = "REQUEST_STUDIO_CATALOG",
  STUDIO_CATALOG = "STUDIO_CATALOG",

  // Diagram Mapping (Phase 2B)
  ANALYZE_PAGE = "ANALYZE_PAGE",
  PAGE_ANALYSIS_RESULT = "PAGE_ANALYSIS_RESULT",
  APPLY_SHAPE_CHANGES = "APPLY_SHAPE_CHANGES",
  APPLY_SHAPE_CHANGES_RESULT = "APPLY_SHAPE_CHANGES_RESULT",
  OPEN_DIAGRAM_MAPPING_MODAL = "OPEN_DIAGRAM_MAPPING_MODAL",
  AUTO_CONVERT_PAGE = "AUTO_CONVERT_PAGE",

  // Embedded scenarios editor — run delegation (Phase 3b)
  RUN_SCENARIO = "RUN_SCENARIO",
  RUN_SCENARIO_RESULT = "RUN_SCENARIO_RESULT",

  // Canvas navigation — locate/select a diagram element from the embedded Studio iframe
  LOCATE_ELEMENT = "LOCATE_ELEMENT",

  // DevTools
  DEVTOOLS_SWIMLANE_SCAN_REQUEST = "DEVTOOLS_SWIMLANE_SCAN_REQUEST",
  DEVTOOLS_SWIMLANE_SCAN_RESULT = "DEVTOOLS_SWIMLANE_SCAN_RESULT",
  DEVTOOLS_KINDE_AUTH_REQUEST = "DEVTOOLS_KINDE_AUTH_REQUEST",
  DEVTOOLS_KINDE_AUTH_RESULT = "DEVTOOLS_KINDE_AUTH_RESULT",

  // Swimlane Operations
  SWIMLANE_UPDATE = "SWIMLANE_UPDATE",
  SWIMLANE_UPDATE_RESULT = "SWIMLANE_UPDATE_RESULT",
  SWIMLANE_CONVERT_LANE = "SWIMLANE_CONVERT_LANE",
  SWIMLANE_CONVERT_LANE_RESULT = "SWIMLANE_CONVERT_LANE_RESULT",

  // Billing & Entitlements (Kinde)
  ENTITLEMENTS_STATUS = "ENTITLEMENTS_STATUS",
  PORTAL_URL_REQUEST = "PORTAL_URL_REQUEST",
  PORTAL_URL_RESPONSE = "PORTAL_URL_RESPONSE",

  // Analytics
  ANALYTICS_TRACK = "ANALYTICS_TRACK"
}
