import React, { useState, useEffect, useCallback } from "react";
import {
  Model,
  PeriodUnit,
  SimulationTimeType,
  SimulationObjectType,
  StateListManager,
  ValidationResult,
} from "@quodsi/shared";
import { Settings, Hash, Info, Users, AlertTriangle } from "lucide-react";
import StatesEditor from "./StatesEditor";
import { AccordionSection } from "../shared/AccordionSection";
import { ResourceRequirementsManager } from "./ResourceRequirementsManager";
import { ResourceRequirementModal } from "./ResourceRequirementModal";
import { convertStructureToRootClauses, convertRootClausesToStructure, TeamStructure } from "../../utils/resourceRequirementConverter";
import { useModelOpsSender } from "../../messaging/senders/modelOpsSender";
import { useElementOpsState } from "../../messaging/hooks/useElementOpsState";
import { useFormSync, useSaveCompletionDetector, useAutoSave, useFlushOnChange } from "./hooks/useEditorState";
import SaveStatusLine from "./SaveStatusLine";
import {
  extractModelData,
  updateModelImmutably,
  isAutoGeneratedRequirement,
  prepareRequirementsForStorage,
  type ModelInput,
} from "../utils/modelEditorHelpers";
import { ValidationDashboard } from "./ValidationDashboard";
import { EditorReferenceData, ResourceRequirement } from "@quodsi/shared";

// ============================================================================
// TYPES
// ============================================================================

interface Props {
  model: Model;
  onSave: (model: Model) => void;
  onRemoveModel?: () => void;
  onValidate?: () => void;
  states: StateListManager;
  onStatesChange: (states: StateListManager) => void;
  referenceData?: EditorReferenceData;
  resourceRequirements?: ResourceRequirement[];
  validationState?: ValidationResult | null;
  activeTab?: EditorTab;
  onTabChange?: (tab: EditorTab) => void;
  onSimulate?: (scenarioName?: string, scenarioDefinitionId?: string, enableAnimation?: boolean) => void;
}

export type EditorTab = "basic" | "states" | "requirements" | "scenarios" | "validation";

/**
 * Type for tracking resource requirement being edited in modal
 */
interface EditingRequirement {
  id: string;
  name: string;
  structure: TeamStructure;
}

/**
 * Tab navigation configuration for ModelEditor.
 * Defines all available tabs, their icons, titles, and tooltips.
 */
const TAB_CONFIG = [
  {
    id: "basic" as const,
    title: "Basic Settings",
    icon: Settings,
    tooltip: "Configure model name, simulation time settings, and runtime parameters"
  },
  {
    id: "states" as const,
    title: "State Definitions",
    icon: Hash,
    tooltip: "Define model-level state variables that can be accessed and modified throughout the simulation"
  },
  {
    id: "requirements" as const,
    title: "Resource Requirements",
    icon: Users,
    tooltip: "Create reusable resource requirement templates that define which resources are needed for activities"
  },
  {
    id: "validation" as const,
    title: "Validation",
    icon: AlertTriangle,
    tooltip: "View comprehensive model validation results and resolve any issues"
  },
];

/**
 * Default random seed value used when no seed is specified.
 * This provides reproducible simulation results for testing and debugging.
 */
const DEFAULT_RANDOM_SEED = 12345;

/**
 * ModelEditor - Component for editing model-level simulation settings
 *
 * The ModelEditor orchestrates the configuration of simulation model settings across
 * multiple tabs, including basic properties, state variables, resource requirements,
 * simulation scenarios, and validation. It acts as a container for specialized sub-editors.
 *
 * Features:
 * - Four-tab interface: Basic Settings, State Definitions, Resource Requirements, and Validation
 * - Controlled component with immediate UI updates
 * - Auto-save for all fields via useAutoSave hook (debounce + onBlur flush;
 *   useFlushOnChange flush for select dropdowns)
 *
 * Tabs:
 * - Basic: Model name, simulation parameters (reps, seed), and time configuration
 * - States: Model-level state variables accessible throughout the simulation
 * - Requirements: Reusable resource requirement templates for activities
 * - Validation: View and resolve model validation issues
 *
 * State Management:
 * - Maintains local draft state (localModelDraft) for immediate UI updates
 * - Syncs with Redux for save state tracking (isSaving)
 * - Uses custom hooks for model switching and save completion detection
 * - Single save path: all Basic-tab field changes route through useAutoSave (debounced)
 *
 * Save Behavior:
 * - Basic tab — Typed inputs (name, reps, runClockPeriod, warmupClockPeriod,
 *   startDateTime, finishDateTime, warmupDateTime): debounced auto-save on edit;
 *   immediate save on blur or element switch.
 * - Basic tab — Selects (simulationTimeType, runClockPeriodUnit, oneClockUnit,
 *   warmupClockPeriodUnit): immediate save via useFlushOnChange (selects have no
 *   useful onBlur).
 * - Save defaulting: onSave is wrapped in onSaveWithDefaults that applies fallbacks
 *   for falsy fields (DEFAULT_RANDOM_SEED for seed, PeriodUnit.HOURS for unit
 *   selectors, etc.) so every saved Model is fully populated even if the user
 *   blanked optional fields.
 * - States tab: Auto-saves immediately via parent onStatesChange.
 * - Requirements tab: Auto-saves immediately via updateResourceRequirements.
 * - Validation tab: Read-only.
 * - Status surfaced via SaveStatusLine ("Saved" / "Saving…" / "Save failed —
 *   keep typing to retry"). Native LucidChart Ctrl+Z reverses saved changes.
 *
 * @param props - Component props
 * @returns Rendered model editor component
 */
const ModelEditor: React.FC<Props> = ({ model, onSave, onRemoveModel, onValidate, states, onStatesChange, referenceData, resourceRequirements, validationState, activeTab: activeTabProp, onTabChange: onTabChangeProp, onSimulate }) => {
  // ============================================================================
  // STATE MANAGEMENT
  // ============================================================================

  // Local state for tab management (used as fallback if props not provided)
  const [localActiveTab, setLocalActiveTab] = useState<EditorTab>("basic");

  // Use props if provided, otherwise fall back to local state (backward compatible)
  const activeTab = activeTabProp ?? localActiveTab;
  const setActiveTab = onTabChangeProp ?? setLocalActiveTab;
  const [requirementModalOpen, setRequirementModalOpen] = useState(false);
  const [editingRequirement, setEditingRequirement] = useState<EditingRequirement | null>(null);
  const [isAdvancedExpanded, setIsAdvancedExpanded] = useState(false); // Start collapsed
  const [showRemoveConfirm, setShowRemoveConfirm] = useState(false);
  const { updateResourceRequirements } = useModelOpsSender();

  // Direct form state management
  const [localModelDraft, setLocalModelDraft] = useState<Model>(() => extractModelData(model));
  const [hasPendingChanges, setHasPendingChanges] = useState(false);

  // Get element operations state from Redux
  const elementOpsState = useElementOpsState();

  /**
   * Redux-managed state for save operation tracking.
   *
   * isSaving: true when save is in progress (shows loading state)
   *
   * This is managed by Redux elementOpsState to coordinate saves across
   * multiple editor instances.
   */
  const isSaving = localModelDraft.id ? elementOpsState.isSaving(localModelDraft.id) : false;

  // Custom hooks for state synchronization
  useFormSync(
    model.id,
    hasPendingChanges,
    () => extractModelData(model),
    setLocalModelDraft,
    setHasPendingChanges
  );

  useSaveCompletionDetector(isSaving, setHasPendingChanges);

  // Wrap onSave with defaulting logic preserved from the deleted handleSave.
  // Auto-save dispatches the raw draft; this callback applies fallbacks for
  // fields that may be falsy (e.g., seed has no UI input — always defaults).
  const onSaveWithDefaults = useCallback(
    (draft: Model) => {
      const modelToSave: Model = {
        ...draft,
        type: "Model" as any, // Cast: SimulationObjectType.Model is enum; type field expects string literal
        reps: draft.reps || 1,
        seed: draft.seed || DEFAULT_RANDOM_SEED,
        simulationTimeType: draft.simulationTimeType || SimulationTimeType.Clock,
        oneClockUnit: draft.oneClockUnit || PeriodUnit.HOURS,
        warmupClockPeriod: draft.warmupClockPeriod || 0,
        warmupClockPeriodUnit: draft.warmupClockPeriodUnit || PeriodUnit.HOURS,
        runClockPeriod: draft.runClockPeriod || 0,
        runClockPeriodUnit: draft.runClockPeriodUnit || PeriodUnit.HOURS,
        warmupDateTime: draft.warmupDateTime || null,
        startDateTime: draft.startDateTime || null,
        finishDateTime: draft.finishDateTime || null,
      };
      onSave(modelToSave);
    },
    [onSave]
  );

  const { status, lastSavedAt, saveNow } = useAutoSave<Model>({
    draft: localModelDraft,
    hasPendingChanges,
    isValid: true, // No validation: only one Model per document, no name-uniqueness check needed.
    onSave: onSaveWithDefaults,
    isSaving,
    elementId: localModelDraft.id,
  });

  // Decisive selects (no useful onBlur): flush save on change.
  useFlushOnChange(localModelDraft.simulationTimeType, saveNow);
  useFlushOnChange(localModelDraft.runClockPeriodUnit, saveNow);
  useFlushOnChange(localModelDraft.oneClockUnit, saveNow);
  useFlushOnChange(localModelDraft.warmupClockPeriodUnit, saveNow);

  // Trigger validation when validation tab is selected
  useEffect(() => {
    if (activeTab === 'validation' && onValidate) {
      onValidate();
    }
  }, [activeTab, onValidate]);

  // Guard against invalid model data
  if (!localModelDraft?.id) {
    return (
      <div className="p-2 bg-red-50 border border-red-200 rounded text-sm">
        <div className="text-red-600 font-medium">Invalid model data</div>
        <div className="text-xs text-red-500 mt-1">Model data missing required properties</div>
      </div>
    );
  }

  // ============================================================================
  // EVENT HANDLERS
  // ============================================================================

  /**
   * Handles changes to form input fields with automatic type conversion.
   *
   * Updates are applied immediately to localModelDraft for responsive UI,
   * and marked as pending. Auto-save fires after debounce (typed inputs),
   * on blur (typed inputs), or via useFlushOnChange (selects).
   *
   * Type conversion:
   * - number inputs: Parsed as float with fallback to 0 for invalid values
   * - datetime-local inputs: Converted to Date objects or null
   * - all other inputs: Kept as strings
   *
   * @param e - Input change event
   */
  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value, type } = e.target;

    // Convert values based on input type
    let convertedValue: string | number | Date | null = value;
    if (type === 'number') {
      const numValue = parseFloat(value);
      convertedValue = isNaN(numValue) ? 0 : numValue;
    } else if (type === 'datetime-local') {
      convertedValue = value ? new Date(value) : null;
    }

    setLocalModelDraft(prev => updateModelImmutably(prev, { [name]: convertedValue } as Partial<Model>));
    setHasPendingChanges(true);
  };

  // ============================================================================
  // RENDER
  // ============================================================================

  return (
    <div className="flex flex-col bg-white">
      <div className="border-b bg-gray-50">
        <div className="flex">
          {TAB_CONFIG.map((tab) => {
            const Icon = tab.icon;
            return (
              <button
                key={tab.id}
                type="button"
                onClick={() => setActiveTab(tab.id)}
                title={tab.tooltip}
                className={`px-3 py-2 border-b-2 ${
                  activeTab === tab.id
                    ? "border-blue-600 text-blue-600"
                    : "border-transparent text-gray-500 hover:text-gray-700"
                }`}
              >
                <Icon className="w-4 h-4" />
              </button>
            );
          })}
        </div>
      </div>

      {activeTab === "basic" && (
        <div className="w-full">
          <div className="space-y-2">
              {/* Model Name - Always Visible WITH LABEL */}
                  <div>
                    <div className="flex items-center gap-1 mb-1">
                      <label className="text-xs font-medium text-gray-700">
                        Model Name
                      </label>
                      <span title="A unique identifier for this simulation model. This name helps you organize and identify different models in your workspace.">
                        <Info className="w-3 h-3 text-gray-400 hover:text-gray-600 cursor-help" />
                      </span>
                    </div>
                    <input
                      type="text"
                      name="name"
                      className="w-full px-2 py-1 text-xs border rounded"
                      value={localModelDraft.name}
                      placeholder="Enter model name"
                      onChange={handleChange}
                      onBlur={saveNow}
                    />
                </div>

                {/* Run Time - Conditional: Only in Clock mode */}
                {localModelDraft.simulationTimeType === SimulationTimeType.Clock && (
                  <div>
                    <div className="flex items-center gap-1 mb-1">
                      <label className="text-xs font-medium text-gray-700">
                        Run Time
                      </label>
                      <span title="The total duration the simulation will run in Clock mode. Specify the time period and unit (e.g., 8 Hours, 30 Days).">
                        <Info className="w-3 h-3 text-gray-400 hover:text-gray-600 cursor-help" />
                      </span>
                    </div>
                    <div className="grid grid-cols-2 gap-1">
                      <input
                        type="number"
                        name="runClockPeriod"
                        className="w-full px-2 py-1 text-xs border rounded"
                        value={localModelDraft.runClockPeriod || 0}
                        onChange={handleChange}
                        min="0"
                        onBlur={saveNow}
                      />
                      <select
                        name="runClockPeriodUnit"
                        className="w-full px-2 py-1 text-xs border rounded bg-white"
                        value={localModelDraft.runClockPeriodUnit || PeriodUnit.HOURS}
                        onChange={handleChange}
                      >
                        {Object.values(PeriodUnit).map((unit) => (
                          <option key={unit} value={unit}>
                            {unit}
                          </option>
                        ))}
                      </select>
                    </div>
                  </div>
                )}

                {/* Advanced Settings - Accordion */}
                <AccordionSection
                  title="Advanced Settings"
                  isExpanded={isAdvancedExpanded}
                  onToggle={() => setIsAdvancedExpanded(!isAdvancedExpanded)}
                >
                  <div className="space-y-2">
                    {/* Replications */}
                    <div>
                      <div className="flex items-center gap-1 mb-1">
                        <label className="text-xs font-medium text-gray-700">
                          Replications
                        </label>
                        <span title="The number of independent simulation runs to perform. Multiple replications help account for randomness and provide statistical confidence in the results.">
                          <Info className="w-3 h-3 text-gray-400 hover:text-gray-600 cursor-help" />
                        </span>
                      </div>
                      <input
                        type="number"
                        name="reps"
                        className="w-full px-2 py-1 text-xs border rounded"
                        value={localModelDraft.reps}
                        onChange={handleChange}
                        min="1"
                        onBlur={saveNow}
                      />
                    </div>

                    {/* Time Mode */}
                    <div>
                      <div className="flex items-center gap-1 mb-1">
                        <label className="text-xs font-medium text-gray-700">
                          Time Mode
                        </label>
                        <span title="Select how time is represented in the simulation. Clock mode uses relative time periods (e.g., Hour 0 to Hour 100), while Calendar Date mode uses actual dates and times.">
                          <Info className="w-3 h-3 text-gray-400 hover:text-gray-600 cursor-help" />
                        </span>
                      </div>
                      <select
                        name="simulationTimeType"
                        className="w-full px-2 py-1 text-xs border rounded bg-white"
                        value={localModelDraft.simulationTimeType}
                        onChange={handleChange}
                      >
                        {Object.values(SimulationTimeType).map((type) => (
                          <option key={type} value={type}>
                            {type}
                          </option>
                        ))}
                      </select>
                    </div>

                    {/* Clock Mode Fields - Conditional */}
                    {localModelDraft.simulationTimeType === SimulationTimeType.Clock && (
                      <>
                        {/* Clock Unit */}
                        <div>
                          <div className="flex items-center gap-1 mb-1">
                            <label className="text-xs font-medium text-gray-700">
                              Clock Unit
                            </label>
                            <span title="The base time unit for the simulation clock (e.g., Minutes, Hours, Days). All time-based values in the model will be expressed in relation to this unit.">
                              <Info className="w-3 h-3 text-gray-400 hover:text-gray-600 cursor-help" />
                            </span>
                          </div>
                          <select
                            name="oneClockUnit"
                            className="w-full px-2 py-1 text-xs border rounded bg-white"
                            value={localModelDraft.oneClockUnit}
                            onChange={handleChange}
                          >
                            {Object.values(PeriodUnit).map((unit) => (
                              <option key={unit} value={unit}>
                                {unit}
                              </option>
                            ))}
                          </select>
                        </div>

                        {/* Warmup Time - Simple number + dropdown */}
                        <div>
                          <div className="flex items-center gap-1 mb-1">
                            <label className="text-xs font-medium text-gray-700">
                              Warmup Time
                            </label>
                            <span title="The initial period during which the simulation reaches steady state. Statistics collected during warmup are discarded to ensure more accurate results.">
                              <Info className="w-3 h-3 text-gray-400 hover:text-gray-600 cursor-help" />
                            </span>
                          </div>
                          <div className="grid grid-cols-2 gap-1">
                            <input
                              type="number"
                              name="warmupClockPeriod"
                              className="w-full px-2 py-1 text-xs border rounded"
                              value={localModelDraft.warmupClockPeriod || 0}
                              onChange={handleChange}
                              min="0"
                              onBlur={saveNow}
                            />
                            <select
                              name="warmupClockPeriodUnit"
                              className="w-full px-2 py-1 text-xs border rounded bg-white"
                              value={localModelDraft.warmupClockPeriodUnit || PeriodUnit.HOURS}
                              onChange={handleChange}
                            >
                              {Object.values(PeriodUnit).map((unit) => (
                                <option key={unit} value={unit}>
                                  {unit}
                                </option>
                              ))}
                            </select>
                          </div>
                        </div>
                      </>
                    )}

                    {/* Calendar Date Mode Fields - Conditional */}
                    {localModelDraft.simulationTimeType === SimulationTimeType.CalendarDate && (
                      <>
                        <div>
                          <div className="flex items-center gap-1 mb-1">
                            <label className="text-xs font-medium text-gray-700">
                              Start Date
                            </label>
                            <span title="The calendar date and time when the simulation begins in Calendar Date mode. Use this to model processes that align with specific real-world dates.">
                              <Info className="w-3 h-3 text-gray-400 hover:text-gray-600 cursor-help" />
                            </span>
                          </div>
                          <input
                            type="datetime-local"
                            name="startDateTime"
                            className="w-full px-2 py-1 text-xs border rounded"
                            value={localModelDraft.startDateTime?.toISOString().slice(0, 16) || ""}
                            onChange={handleChange}
                            onBlur={saveNow}
                          />
                        </div>
                        <div>
                          <div className="flex items-center gap-1 mb-1">
                            <label className="text-xs font-medium text-gray-700">
                              Finish Date
                            </label>
                            <span title="The calendar date and time when the simulation ends in Calendar Date mode. The simulation will run from Start Date to this Finish Date.">
                              <Info className="w-3 h-3 text-gray-400 hover:text-gray-600 cursor-help" />
                            </span>
                          </div>
                          <input
                            type="datetime-local"
                            name="finishDateTime"
                            className="w-full px-2 py-1 text-xs border rounded"
                            value={localModelDraft.finishDateTime?.toISOString().slice(0, 16) || ""}
                            onChange={handleChange}
                            onBlur={saveNow}
                          />
                        </div>
                        <div>
                          <div className="flex items-center gap-1 mb-1">
                            <label className="text-xs font-medium text-gray-700">
                              Warmup Date
                            </label>
                            <span title="The calendar date and time when the warmup period ends and statistics collection begins in Calendar Date mode. Set this between Start Date and Finish Date.">
                              <Info className="w-3 h-3 text-gray-400 hover:text-gray-600 cursor-help" />
                            </span>
                          </div>
                          <input
                            type="datetime-local"
                            name="warmupDateTime"
                            className="w-full px-2 py-1 text-xs border rounded"
                            value={localModelDraft.warmupDateTime?.toISOString().slice(0, 16) || ""}
                            onChange={handleChange}
                            onBlur={saveNow}
                          />
                        </div>
                      </>
                    )}
                  </div>
                </AccordionSection>

                {/* Auto-save status */}
                <SaveStatusLine status={status} lastSavedAt={lastSavedAt} />
              </div>
          </div>
      )}
      {activeTab === "states" && (
        <StatesEditor
            states={states}
            onStatesChange={onStatesChange}
            defaultComponentType="ALL"
          />
      )}
      {activeTab === "requirements" && (
        <ResourceRequirementsManager
            requirements={resourceRequirements || []}
            availableResources={referenceData?.resources || []}
            onAdd={() => {
              setEditingRequirement(null);
              setRequirementModalOpen(true);
            }}
            onEdit={(req) => {
              const structure = convertRootClausesToStructure(req.rootClauses);
              setEditingRequirement({ id: req.id, name: req.name, structure });
              setRequirementModalOpen(true);
            }}
            onDelete={(id) => {
              const remainingRequirements = (resourceRequirements || []).filter(req => req.id !== id);
              const requirementsPayload = prepareRequirementsForStorage(
                remainingRequirements,
                referenceData?.resources || []
              );
              updateResourceRequirements(requirementsPayload);
            }}
            getUsageCount={(id) => {
              // Calculate how many actions use this requirement
              const activities = referenceData?.activities || [];
              let count = 0;
              for (const activity of activities) {
                const reqIds = activity.actionRequirementIds || [];
                count += reqIds.filter(reqId => reqId === id).length;
              }
              return count;
            }}
          />
      )}
      {activeTab === "validation" && (
        <ValidationDashboard
          validationState={validationState || null}
          referenceData={referenceData}
        />
      )}

      {/* Resource Requirement Modal */}
      <ResourceRequirementModal
        isOpen={requirementModalOpen}
        onClose={() => {
          setRequirementModalOpen(false);
          setEditingRequirement(null);
        }}
        onSave={(data) => {
          const rootClauses = convertStructureToRootClauses(data.structure);

          // Create the updated/new requirement
          let savedRequirement: ResourceRequirement;
          let updatedRequirementsList: ResourceRequirement[];

          if (editingRequirement) {
            // Update existing requirement (could be editing auto or custom)
            savedRequirement = new ResourceRequirement(editingRequirement.id, data.name, rootClauses);
            updatedRequirementsList = (resourceRequirements || []).map(req =>
              req.id === editingRequirement.id ? savedRequirement : req
            );
          } else {
            // Create new requirement (always custom)
            savedRequirement = new ResourceRequirement(`req-${Date.now()}`, data.name, rootClauses);
            updatedRequirementsList = [...(resourceRequirements || []), savedRequirement];
          }

          // IMPORTANT: Only send custom requirements to storage (filter out unmodified auto-requirements)
          // - New requirements (ID starts with "req-") are always custom
          // - Edited requirements (even if ID matches resource) become custom overrides
          // - Unmodified auto-requirements (ID matches resource, wasn't just edited) are filtered out
          const customRequirementsToSave = updatedRequirementsList.filter(req =>
            !isAutoGeneratedRequirement(req, referenceData?.resources || []) || req.id === savedRequirement.id
          );

          // Serialize for storage
          const savePayload = customRequirementsToSave.map(req => ({
            id: req.id,
            name: req.name,
            type: SimulationObjectType.ResourceRequirement,
            rootClauses: req.rootClauses
          }));

          // Send custom-only array to extension
          updateResourceRequirements(savePayload);

          // Close modal
          setRequirementModalOpen(false);
          setEditingRequirement(null);
        }}
        editingRequirement={editingRequirement}
        availableResources={referenceData?.resources || []}
      />
    </div>
  );
};

export default React.memo(ModelEditor);
