import React, { useState, useEffect, useMemo, useCallback, useRef } from "react";
import {
  Model,
  PeriodUnit,
  SimulationTimeType,
  SimulationObjectType,
  StateListManager,
  ValidationResult,
  RunState,
  EnvelopeMessageType,
  EnvelopeBase,
  SimulationRunInfo,
  generateUUID,
} from "@quodsi/shared";
import { Settings, Hash, PlaySquare, Info, Users, AlertTriangle, Plus, RefreshCw, Loader2 } from "lucide-react";
import StatesEditor from "./StatesEditor";
import { AccordionSection } from "../shared/AccordionSection";
import { ScenarioCard, ScenarioRunStatus } from "./ScenarioCard";
import { ResourceRequirementsManager } from "./ResourceRequirementsManager";
import { ResourceRequirementModal } from "./ResourceRequirementModal";
import { convertStructureToRootClauses, convertRootClausesToStructure, TeamStructure } from "../../utils/resourceRequirementConverter";
import { useMessaging, useSimulationRuns, useMessagingDispatch, useEntitlements } from "../../messaging/MessageProvider";
import { useSync } from "../../messaging/MessageContext";
import { canRunNewScenario, scenariosPerModelLimit } from "../../messaging/state/entitlementsSlice";
import { useModelOpsSender } from "../../messaging/senders/modelOpsSender";
import { useSimulationRunSender } from "../../messaging/senders/simulationRunSender";
import { useSyncSender } from "../../messaging/senders/syncSender";
import { useScenariosSender } from "../../messaging/senders/scenariosSender";
import { selectSimulationRuns } from "../../messaging/state/simulationRunSlice";
import { ISerializedScenario } from "@quodsi/shared";
import { useElementOpsState } from "../../messaging/hooks/useElementOpsState";
import { useFormSync, useSaveCompletionDetector, useAutoSave, useFlushOnChange } from "./hooks/useEditorState";
import SaveStatusLine from "./SaveStatusLine";
import {
  extractModelData,
  updateModelImmutably,
  isAutoGeneratedRequirement,
  prepareRequirementsForStorage,
  type ModelInput,
} from "../utils/modelEditorHelpers";
import { ValidationDashboard } from "./ValidationDashboard";

import { EditorReferenceData, ResourceRequirement } from "@quodsi/shared";

// ============================================================================
// TYPES
// ============================================================================

interface Props {
  model: Model;
  onSave: (model: Model) => void;
  onRemoveModel?: () => void;
  onValidate?: () => void;
  states: StateListManager;
  onStatesChange: (states: StateListManager) => void;
  referenceData?: EditorReferenceData;
  resourceRequirements?: ResourceRequirement[];
  validationState?: ValidationResult | null;
  activeTab?: EditorTab;
  onTabChange?: (tab: EditorTab) => void;
  onSimulate?: (scenarioName?: string, scenarioDefinitionId?: string) => void;
}

export type EditorTab = "basic" | "states" | "requirements" | "scenarios" | "validation";

/**
 * Type for tracking resource requirement being edited in modal
 */
interface EditingRequirement {
  id: string;
  name: string;
  structure: TeamStructure;
}

/**
 * Tab navigation configuration for ModelEditor.
 * Defines all available tabs, their icons, titles, and tooltips.
 */
const TAB_CONFIG = [
  {
    id: "basic" as const,
    title: "Basic Settings",
    icon: Settings,
    tooltip: "Configure model name, simulation time settings, and runtime parameters"
  },
  {
    id: "states" as const,
    title: "State Definitions",
    icon: Hash,
    tooltip: "Define model-level state variables that can be accessed and modified throughout the simulation"
  },
  {
    id: "requirements" as const,
    title: "Resource Requirements",
    icon: Users,
    tooltip: "Create reusable resource requirement templates that define which resources are needed for activities"
  },
  {
    id: "scenarios" as const,
    title: "Scenarios",
    icon: PlaySquare,
    tooltip: "Configure and manage scenarios with different parameter sets and run configurations"
  },
  {
    id: "validation" as const,
    title: "Validation",
    icon: AlertTriangle,
    tooltip: "View comprehensive model validation results and resolve any issues"
  },
];

/**
 * Default random seed value used when no seed is specified.
 * This provides reproducible simulation results for testing and debugging.
 */
const DEFAULT_RANDOM_SEED = 12345;


/**
 * Maps SimulationStatus string values to RunState enum values.
 */
function mapStatusToRunState(status: string): RunState {
  switch (status.toLowerCase()) {
    case 'queued':
      return RunState.Queued;
    case 'processing':
    case 'validating':
    case 'running':
      return RunState.Running;
    case 'completed':
      return RunState.RanSuccessfully;
    case 'failed':
    case 'error':
      return RunState.RanWithErrors;
    default:
      return RunState.NotRun;
  }
}

type AutoRefreshMode = 'off' | 'smart' | 'on';

/**
 * Unified panel that combines scenario management with smart polling
 * and analysis navigation. Replaces the old sub-tab (Scenarios | Runs) pattern
 * with an integrated view where each scenario shows its run status inline.
 *
 * Exported (named export only) for unit testing — the outer ModelEditor still
 * remains the default export. Production code should keep using ModelEditor
 * which renders this internally when the "scenarios" tab is active.
 */
export const ScenariosAndRunsPanel: React.FC<{
  documentId?: string;
  pageId?: string;
  modelName: string;
  referenceData?: EditorReferenceData;
  onScenariosChange: (scenarios: ISerializedScenario[]) => void;
  onSimulate: (scenarioName?: string, scenarioDefinitionId?: string) => void;
}> = ({ documentId, pageId, modelName, referenceData, onScenariosChange, onSimulate }) => {
  const [expandedScenarioId, setExpandedScenarioId] = useState<string | null>(null);
  const [deletingScenarioId, setDeletingScenarioId] = useState<string | null>(null);
  const [rerunningScenarioId, setRerunningScenarioId] = useState<string | null>(null);
  const [autoRefreshMode, setAutoRefreshMode] = useState<AutoRefreshMode>('off');
  // Messaging hooks
  const { listSimulationRuns, deleteSimulationRun, openResultsModal } = useSimulationRunSender();
  const { syncAll } = useSyncSender();
  const { listScenarios } = useScenariosSender();
  const dispatch = useMessagingDispatch();
  const simulationRunState = useSimulationRuns();
  const simulationRuns = selectSimulationRuns({ simulationRuns: simulationRunState });
  const simulationRunsLoading = simulationRunState.loading;
  const { isSyncing } = useSync();

  // Ref to track current simulation runs without causing dependency cycles
  const simulationRunsRef = useRef(simulationRuns);
  simulationRunsRef.current = simulationRuns;

  // Ref to access documentId from message handler without adding it as a useEffect dependency
  const documentIdRef = useRef(documentId);
  documentIdRef.current = documentId;

  // Scenarios from reference data
  const scenarios: ISerializedScenario[] = referenceData?.scenarios ?? [];

  // --- entitlement gating for per-scenario Run ---
  // `scenarios_per_model` caps the number of DISTINCT scenarios that
  // have ever been run for this model. Re-runs are free; the first run
  // of a new scenario consumes a slot. Adding/defining scenarios is
  // unmetered. Server is the authoritative gate; this just greys out
  // the per-scenario Run button proactively.
  const entitlements = useEntitlements();
  const scenarioCapLimit = scenariosPerModelLimit(entitlements);

  // Build a map from scenario id to run status
  // Since run.id = scenario definition ID (blob folder = def ID), map directly by run.id
  const runStatusMap = useMemo(() => {
    const map = new Map<string, ScenarioRunStatus>();
    for (const run of simulationRuns) {
      if (!map.has(run.id)) {
        map.set(run.id, {
          scenarioId: run.id,
          status: run.runState,
          hasResults: run.hasResults,
          downloadInfo: run.downloadInfo,
          error: run.error,
          errorType: run.errorType,
          errorDetails: run.errorDetails,
          errorSuggestions: run.errorSuggestions,
          currentReplication: run.currentReplication,
          reps: run.reps,
        });
      }
    }
    return map;
  }, [simulationRuns]);

  // Distinct-runs count for the scenarios_per_model cap. A scenario
  // counts iff its run state is anything other than NotRun. Used below
  // to decide which per-scenario Run buttons to grey out.
  const distinctRunsCount = useMemo(
    () =>
      scenarios.reduce((acc, s) => {
        const st = runStatusMap.get(s.id)?.status;
        return acc + (st && st !== RunState.NotRun ? 1 : 0);
      }, 0),
    [scenarios, runStatusMap],
  );
  const newScenarioRunBlocked =
    entitlements.loaded && !canRunNewScenario(entitlements, distinctRunsCount);

  // Execute the actual play/simulate action with optimistic update
  const executePlay = useCallback((scenario: ISerializedScenario) => {
    onSimulate(scenario.name, scenario.id);

    // Optimistic update: immediately show Queued status so the play button
    // becomes a spinner without waiting for the server round-trip.
    const optimisticRun: SimulationRunInfo = {
      id: scenario.id,
      name: scenario.name,
      runState: RunState.Queued,
      reps: 0,
      runClockPeriod: 0,
      runClockPeriodUnit: 'Minutes',
      simulationTimeType: 'Clock',
      hasResults: false,
      outputSchemaVersion: null,
      engineVersion: null,
    };
    const currentRuns = simulationRunsRef.current;
    dispatch({
      type: 'SIMULATION_RUNS_SUCCESS',
      simulationRuns: [optimisticRun, ...currentRuns.filter(r => r.id !== scenario.id)],
    });
    // Enable smart auto-refresh to start polling for real status
    setAutoRefreshMode(prev => prev === 'off' ? 'smart' : prev);
    setRerunningScenarioId(null);
  }, [onSimulate, dispatch]);

  // Play button handler — confirm before re-running if results already exist
  const handlePlay = useCallback((scenario: ISerializedScenario) => {
    const existingRun = runStatusMap.get(scenario.id);
    if (existingRun?.hasResults) {
      setRerunningScenarioId(scenario.id);
      setDeletingScenarioId(null);
      return;
    }
    executePlay(scenario);
  }, [runStatusMap, executePlay]);

  // Scenario management handlers
  const handleAddScenario = useCallback(() => {
    const newScenario: ISerializedScenario = {
      id: generateUUID(),
      name: `Scenario ${scenarios.filter(s => !s.isBaseline).length + 1}`,
      changeRequests: [],
    };
    onScenariosChange([...scenarios, newScenario]);
    setExpandedScenarioId(newScenario.id);
  }, [scenarios, onScenariosChange]);

  const confirmRerun = useCallback(() => {
    const scenario = scenarios.find(s => s.id === rerunningScenarioId);
    if (scenario) executePlay(scenario);
  }, [rerunningScenarioId, scenarios, executePlay]);

  const cancelRerun = useCallback(() => {
    setRerunningScenarioId(null);
  }, []);

  const handleDeleteScenario = useCallback((scenarioId: string) => {
    setDeletingScenarioId(scenarioId);
    setRerunningScenarioId(null);
  }, []);

  const confirmDeleteScenario = useCallback(() => {
    if (!deletingScenarioId) return;
    const existingRun = runStatusMap.get(deletingScenarioId);
    if (existingRun && documentId) {
      deleteSimulationRun(documentId, existingRun.scenarioId);
    }
    onScenariosChange(scenarios.filter(s => s.id !== deletingScenarioId));
    if (expandedScenarioId === deletingScenarioId) {
      setExpandedScenarioId(null);
    }
    setDeletingScenarioId(null);
  }, [deletingScenarioId, scenarios, onScenariosChange, expandedScenarioId, runStatusMap, documentId, deleteSimulationRun]);

  const cancelDeleteScenario = useCallback(() => {
    setDeletingScenarioId(null);
  }, []);

  const handleUpdateScenario = useCallback((updated: ISerializedScenario) => {
    onScenariosChange(scenarios.map(s => s.id === updated.id ? updated : s));
  }, [scenarios, onScenariosChange]);

  /**
   * Pull-only callback for refreshing canonical state from the server.
   * Explicitly calls both listScenarios and listSimulationRuns for code clarity,
   * though the backend currently returns scenarios with nested runs in a single response.
   *
   * Renamed from `loadSimulationRuns` for naming honesty: it pulls everything,
   * not just runs. Manual user clicks now use `handleSync` (which does the full
   * bidirectional reconcile: UpsertModel + SyncScenarios + ListScenarios +
   * ListSimulationRuns); this callback drives the read-only pull path used by
   * the initial-load effect and is intended for the auto-refresh polling timer.
   *
   * The explicit listScenarios call is belt-and-suspenders: currently redundant
   * since runs come nested in the ListScenarios response, but defensive against
   * future backend changes that might split the responses.
   */
  const loadFromServer = useCallback(() => {
    if (!documentId || !pageId) return;
    dispatch({ type: 'SIMULATION_RUNS_LOADING' });
    // Pull scenarios + runs explicitly. Backend currently returns runs nested
    // in the ListScenarios response, so this is technically belt-and-suspenders,
    // but it makes intent visible and resilient if the backend ever splits the
    // responses.
    listScenarios(documentId, pageId);
    listSimulationRuns(documentId);
  }, [documentId, pageId, listScenarios, listSimulationRuns, dispatch]);

  // Sync model + scenarios with the server. Fire-and-forget — the extension
  // dispatches SYNC_ALL_SUCCESS_UPDATE / SYNC_ALL_ERROR_UPDATE via the sync
  // mapper when it sends SYNC_ALL_SUCCESS / SYNC_ALL_ERROR back, which clears
  // isSyncing in the Redux sync slice.
  const handleSync = useCallback(() => {
    if (isSyncing) return;
    if (!documentId || !pageId) return;
    // Mark in-flight optimistically.
    dispatch({ type: 'SYNC_ALL_START' });
    syncAll(documentId, pageId, modelName, scenarios);
  }, [isSyncing, dispatch, syncAll, documentId, pageId, modelName, scenarios]);

  // Message listener for simulation run updates
  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      const message = event.data as EnvelopeBase;
      if (!message?.type) return;

      if (message.type === EnvelopeMessageType.SIMULATION_RUNS_LIST_RESULT) {
        const runs: SimulationRunInfo[] = (message as any).data?.scenarios || [];
        // Preserve optimistic runs that haven't appeared in the server list yet
        const currentRuns = simulationRunsRef.current;
        const incomingIds = new Set(runs.map(s => s.id));
        const optimisticRuns = currentRuns.filter(s =>
          !incomingIds.has(s.id) &&
          (s.runState === RunState.Queued || s.runState === RunState.Running)
        );
        dispatch({ type: 'SIMULATION_RUNS_SUCCESS', simulationRuns: [...optimisticRuns, ...runs] });
      } else if (message.type === EnvelopeMessageType.MODEL_RUN_STATUS) {
        const statusData = (message as any).data;
        if (statusData?.scenarioId) {
          if (statusData.scenarioId === 'error' && statusData.status === 'failed') {
            dispatch({ type: 'SIMULATION_RUNS_ERROR', error: statusData.error || 'Simulation failed' });
            return;
          }
          const currentRuns = simulationRunsRef.current;
          const existing = currentRuns.find(r => r.id === statusData.scenarioId);
          if (existing) {
            const newRunState = mapStatusToRunState(statusData.status);
            // For failed status with error info, update the full run object to include error fields
            if (newRunState === RunState.RanWithErrors && statusData.error) {
              dispatch({
                type: 'SIMULATION_RUNS_SUCCESS',
                simulationRuns: currentRuns.map(r =>
                  r.id === statusData.scenarioId
                    ? {
                        ...r,
                        runState: RunState.RanWithErrors,
                        hasResults: false,
                        error: statusData.error,
                        errorType: statusData.errorType,
                        errorDetails: statusData.errorDetails,
                        errorSuggestions: statusData.errorSuggestions,
                      }
                    : r
                ),
              });
            } else {
              dispatch({
                type: 'SIMULATION_RUN_UPDATE_STATUS',
                simulationRunId: statusData.scenarioId,
                runState: newRunState,
                hasResults: statusData.status === 'completed' || statusData.hasResults || false,
              });
            }
            // Immediately refresh to get downloadInfo for completed/failed runs
            if (newRunState === RunState.RanSuccessfully || newRunState === RunState.RanWithErrors) {
              const docId = documentIdRef.current;
              if (docId) listSimulationRuns(docId);
            }
          } else if (statusData.status === 'queued' || statusData.status === 'processing') {
            const newRun: SimulationRunInfo = {
              id: statusData.scenarioId,
              name: statusData.scenarioName || 'New Simulation',
              runState: mapStatusToRunState(statusData.status),
              reps: statusData.reps || 0,
              runClockPeriod: statusData.runClockPeriod || 0,
              runClockPeriodUnit: statusData.runClockPeriodUnit || 'Minutes',
              simulationTimeType: statusData.simulationTimeType || 'Clock',
              completedAt: statusData.queuedAt,
              hasResults: false,
              outputSchemaVersion: null,
              engineVersion: null,
            };
            dispatch({ type: 'SIMULATION_RUNS_SUCCESS', simulationRuns: [newRun, ...currentRuns] });
            setAutoRefreshMode(prev => prev === 'off' ? 'smart' : prev);
          }
        }
      }
    };
    window.addEventListener('message', handleMessage);
    return () => window.removeEventListener('message', handleMessage);
  }, [dispatch, listSimulationRuns]);

  // Initial load
  useEffect(() => {
    if (documentId) {
      loadFromServer();
    }
  }, [documentId, loadFromServer]);

  // Polling
  useEffect(() => {
    if (autoRefreshMode === 'off' || !documentId) return;

    if (autoRefreshMode === 'smart') {
      const hasActive = simulationRuns.some(r => r.runState === RunState.Running || r.runState === RunState.Queued);
      const needsDownloadInfo = simulationRuns.some(r =>
        r.runState === RunState.RanSuccessfully && r.hasResults && !r.downloadInfo
      );
      if (!hasActive && !needsDownloadInfo) return;
    }

    const interval = setInterval(() => {
      listSimulationRuns(documentId);
    }, 10000);

    return () => clearInterval(interval);
  }, [autoRefreshMode, simulationRuns, documentId, listSimulationRuns]);

  return (
    <div className="flex flex-col h-full">
      {/* Scenario Card List — flat scrollable list, each card expands inline */}
      <div className="flex-1 overflow-y-auto p-2 space-y-1">
        {simulationRunsLoading && simulationRuns.length === 0 ? (
          <div className="flex items-center justify-center py-8">
            <Loader2 className="w-5 h-5 animate-spin text-blue-600" />
            <span className="ml-2 text-sm text-gray-500">Loading runs...</span>
          </div>
        ) : (
          scenarios.map(scenario => {
            const scenarioStatus = runStatusMap.get(scenario.id)?.status;
            const hasBeenRun = !!scenarioStatus && scenarioStatus !== RunState.NotRun;
            // Block running this scenario only if it's a NEW scenario (never run)
            // and we're already at the distinct-runs cap. Re-runs are always free.
            const runCapBlocked = !hasBeenRun && newScenarioRunBlocked;
            const runCapTooltip = runCapBlocked && scenarioCapLimit !== null
              ? `Your plan allows running up to ${scenarioCapLimit} distinct ${scenarioCapLimit === 1 ? "scenario" : "scenarios"} per model. Re-runs are free, but you've already started runs for ${distinctRunsCount} different ${distinctRunsCount === 1 ? "scenario" : "scenarios"}. Delete one or upgrade to run a new one.`
              : undefined;
            return (
              <ScenarioCard
                key={scenario.id}
                scenario={scenario}
                runStatus={runStatusMap.get(scenario.id)}
                referenceData={referenceData}
                expanded={expandedScenarioId === scenario.id}
                onToggleExpand={() =>
                  setExpandedScenarioId(expandedScenarioId === scenario.id ? null : scenario.id)
                }
                onPlay={() => handlePlay(scenario)}
                runCapBlocked={runCapBlocked}
                runCapTooltip={runCapTooltip}
                onDelete={scenario.isBaseline ? undefined : () => handleDeleteScenario(scenario.id)}
                onUpdate={handleUpdateScenario}
                onAnalyze={(scenarioId) => {
                  if (documentId) {
                    openResultsModal(documentId, scenarioId);
                  }
                }}
              />
            );
          })
        )}
        {deletingScenarioId && (
          <div className="p-3 bg-red-50 border border-red-200 rounded">
            <div className="text-xs font-medium text-red-900 mb-2">
              Delete scenario "{scenarios.find(s => s.id === deletingScenarioId)?.name ?? deletingScenarioId}"?
            </div>
            <div className="text-xs text-red-700 mb-3">
              This will also remove any associated simulation results. This action cannot be undone.
            </div>
            <div className="flex gap-2">
              <button
                onClick={confirmDeleteScenario}
                className="px-3 py-1 text-xs bg-red-600 text-white rounded hover:bg-red-700"
              >
                Delete
              </button>
              <button
                onClick={cancelDeleteScenario}
                className="px-3 py-1 text-xs bg-gray-200 text-gray-700 rounded hover:bg-gray-300"
              >
                Cancel
              </button>
            </div>
          </div>
        )}
        {rerunningScenarioId && (
          <div className="p-3 bg-yellow-50 border border-yellow-200 rounded">
            <div className="text-xs font-medium text-yellow-900 mb-2">
              Re-run scenario "{scenarios.find(s => s.id === rerunningScenarioId)?.name ?? rerunningScenarioId}"?
            </div>
            <div className="text-xs text-yellow-700 mb-3">
              This will replace the existing simulation results. This action cannot be undone.
            </div>
            <div className="flex gap-2">
              <button
                onClick={confirmRerun}
                className="px-3 py-1 text-xs bg-yellow-600 text-white rounded hover:bg-yellow-700"
              >
                Re-run
              </button>
              <button
                onClick={cancelRerun}
                className="px-3 py-1 text-xs bg-gray-200 text-gray-700 rounded hover:bg-gray-300"
              >
                Cancel
              </button>
            </div>
          </div>
        )}
        <button
          onClick={handleAddScenario}
          className="flex items-center gap-1 w-full px-3 py-2 text-xs transition-colors rounded text-blue-600 hover:bg-blue-50"
          title="Add another scenario to this model"
        >
          <Plus className="w-3 h-3" />
          Add Scenario
        </button>
      </div>

      {/* Auto-refresh control */}
      <div className="flex items-center justify-end gap-2 px-3 py-1.5 border-t bg-gray-50">
        <button
          onClick={handleSync}
          disabled={isSyncing || !documentId || !pageId}
          aria-busy={isSyncing}
          className="p-1 text-gray-500 hover:text-blue-600 hover:bg-blue-50 rounded transition-colors disabled:opacity-50 disabled:cursor-wait"
          title={isSyncing ? 'Syncing...' : 'Sync (push local changes, pull server updates)'}
        >
          <RefreshCw className={`w-3.5 h-3.5 ${isSyncing ? 'animate-spin' : ''}`} />
        </button>
        <select
          value={autoRefreshMode}
          onChange={(e) => setAutoRefreshMode(e.target.value as AutoRefreshMode)}
          className="text-xs border border-gray-300 rounded px-1 py-1 bg-white"
          title="Auto-refresh mode"
        >
          <option value="off">Auto: Off</option>
          <option value="smart">Auto: Smart</option>
          <option value="on">Auto: On</option>
        </select>
      </div>
    </div>
  );
};

/**
 * ModelEditor - Component for editing model-level simulation settings
 *
 * The ModelEditor orchestrates the configuration of simulation model settings across
 * multiple tabs, including basic properties, state variables, resource requirements,
 * simulation scenarios, and validation. It acts as a container for specialized sub-editors.
 *
 * Features:
 * - Five-tab interface: Basic Settings, State Definitions, Resource Requirements, Scenarios, and Validation
 * - Controlled component with immediate UI updates
 * - Auto-save for all fields via useAutoSave hook (debounce + onBlur flush;
 *   useFlushOnChange flush for select dropdowns)
 *
 * Tabs:
 * - Basic: Model name, simulation parameters (reps, seed), and time configuration
 * - States: Model-level state variables accessible throughout the simulation
 * - Requirements: Reusable resource requirement templates for activities
 * - Scenarios: Simulation scenario configuration and management
 * - Validation: View and resolve model validation issues
 *
 * State Management:
 * - Maintains local draft state (localModelDraft) for immediate UI updates
 * - Syncs with Redux for save state tracking (isSaving)
 * - Uses custom hooks for model switching and save completion detection
 * - Single save path: all Basic-tab field changes route through useAutoSave (debounced)
 *
 * Save Behavior:
 * - Basic tab — Typed inputs (name, reps, runClockPeriod, warmupClockPeriod,
 *   startDateTime, finishDateTime, warmupDateTime): debounced auto-save on edit;
 *   immediate save on blur or element switch.
 * - Basic tab — Selects (simulationTimeType, runClockPeriodUnit, oneClockUnit,
 *   warmupClockPeriodUnit): immediate save via useFlushOnChange (selects have no
 *   useful onBlur).
 * - Save defaulting: onSave is wrapped in onSaveWithDefaults that applies fallbacks
 *   for falsy fields (DEFAULT_RANDOM_SEED for seed, PeriodUnit.HOURS for unit
 *   selectors, etc.) so every saved Model is fully populated even if the user
 *   blanked optional fields.
 * - States tab: Auto-saves immediately via parent onStatesChange.
 * - Requirements tab: Auto-saves immediately via updateResourceRequirements.
 * - Scenarios tab: Auto-saves immediately via updateScenarioDefinitions.
 * - Validation tab: Read-only.
 * - Status surfaced via SaveStatusLine ("Saved" / "Saving…" / "Save failed —
 *   keep typing to retry"). Native LucidChart Ctrl+Z reverses saved changes.
 *
 * @param props - Component props
 * @returns Rendered model editor component
 */
const ModelEditor: React.FC<Props> = ({ model, onSave, onRemoveModel, onValidate, states, onStatesChange, referenceData, resourceRequirements, validationState, activeTab: activeTabProp, onTabChange: onTabChangeProp, onSimulate }) => {
  // ============================================================================
  // STATE MANAGEMENT
  // ============================================================================

  // Local state for tab management (used as fallback if props not provided)
  const [localActiveTab, setLocalActiveTab] = useState<EditorTab>("basic");

  // Use props if provided, otherwise fall back to local state (backward compatible)
  const activeTab = activeTabProp ?? localActiveTab;
  const setActiveTab = onTabChangeProp ?? setLocalActiveTab;
  const [requirementModalOpen, setRequirementModalOpen] = useState(false);
  const [editingRequirement, setEditingRequirement] = useState<EditingRequirement | null>(null);
  const [isAdvancedExpanded, setIsAdvancedExpanded] = useState(false); // Start collapsed
  const [showRemoveConfirm, setShowRemoveConfirm] = useState(false);
  const { selection } = useMessaging();
  const { updateResourceRequirements, updateScenarioDefinitions } = useModelOpsSender();

  // Direct form state management
  const [localModelDraft, setLocalModelDraft] = useState<Model>(() => extractModelData(model));
  const [hasPendingChanges, setHasPendingChanges] = useState(false);

  // Get element operations state from Redux
  const elementOpsState = useElementOpsState();

  /**
   * Redux-managed state for save operation tracking.
   *
   * isSaving: true when save is in progress (shows loading state)
   *
   * This is managed by Redux elementOpsState to coordinate saves across
   * multiple editor instances.
   */
  const isSaving = localModelDraft.id ? elementOpsState.isSaving(localModelDraft.id) : false;

  // Custom hooks for state synchronization
  useFormSync(
    model.id,
    hasPendingChanges,
    () => extractModelData(model),
    setLocalModelDraft,
    setHasPendingChanges
  );

  useSaveCompletionDetector(isSaving, setHasPendingChanges);

  // Wrap onSave with defaulting logic preserved from the deleted handleSave.
  // Auto-save dispatches the raw draft; this callback applies fallbacks for
  // fields that may be falsy (e.g., seed has no UI input — always defaults).
  const onSaveWithDefaults = useCallback(
    (draft: Model) => {
      const modelToSave: Model = {
        ...draft,
        type: "Model" as any, // Cast: SimulationObjectType.Model is enum; type field expects string literal
        reps: draft.reps || 1,
        seed: draft.seed || DEFAULT_RANDOM_SEED,
        simulationTimeType: draft.simulationTimeType || SimulationTimeType.Clock,
        oneClockUnit: draft.oneClockUnit || PeriodUnit.HOURS,
        warmupClockPeriod: draft.warmupClockPeriod || 0,
        warmupClockPeriodUnit: draft.warmupClockPeriodUnit || PeriodUnit.HOURS,
        runClockPeriod: draft.runClockPeriod || 0,
        runClockPeriodUnit: draft.runClockPeriodUnit || PeriodUnit.HOURS,
        warmupDateTime: draft.warmupDateTime || null,
        startDateTime: draft.startDateTime || null,
        finishDateTime: draft.finishDateTime || null,
      };
      onSave(modelToSave);
    },
    [onSave]
  );

  const { status, lastSavedAt, saveNow } = useAutoSave<Model>({
    draft: localModelDraft,
    hasPendingChanges,
    isValid: true, // No validation: only one Model per document, no name-uniqueness check needed.
    onSave: onSaveWithDefaults,
    isSaving,
    elementId: localModelDraft.id,
  });

  // Decisive selects (no useful onBlur): flush save on change.
  useFlushOnChange(localModelDraft.simulationTimeType, saveNow);
  useFlushOnChange(localModelDraft.runClockPeriodUnit, saveNow);
  useFlushOnChange(localModelDraft.oneClockUnit, saveNow);
  useFlushOnChange(localModelDraft.warmupClockPeriodUnit, saveNow);

  // Trigger validation when validation tab is selected
  useEffect(() => {
    if (activeTab === 'validation' && onValidate) {
      onValidate();
    }
  }, [activeTab, onValidate]);

  // Guard against invalid model data
  if (!localModelDraft?.id) {
    return (
      <div className="p-2 bg-red-50 border border-red-200 rounded text-sm">
        <div className="text-red-600 font-medium">Invalid model data</div>
        <div className="text-xs text-red-500 mt-1">Model data missing required properties</div>
      </div>
    );
  }

  // ============================================================================
  // EVENT HANDLERS
  // ============================================================================

  /**
   * Handles changes to form input fields with automatic type conversion.
   *
   * Updates are applied immediately to localModelDraft for responsive UI,
   * and marked as pending. Auto-save fires after debounce (typed inputs),
   * on blur (typed inputs), or via useFlushOnChange (selects).
   *
   * Type conversion:
   * - number inputs: Parsed as float with fallback to 0 for invalid values
   * - datetime-local inputs: Converted to Date objects or null
   * - all other inputs: Kept as strings
   *
   * @param e - Input change event
   */
  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value, type } = e.target;

    // Convert values based on input type
    let convertedValue: string | number | Date | null = value;
    if (type === 'number') {
      const numValue = parseFloat(value);
      convertedValue = isNaN(numValue) ? 0 : numValue;
    } else if (type === 'datetime-local') {
      convertedValue = value ? new Date(value) : null;
    }

    setLocalModelDraft(prev => updateModelImmutably(prev, { [name]: convertedValue } as Partial<Model>));
    setHasPendingChanges(true);
  };

  // ============================================================================
  // RENDER
  // ============================================================================

  return (
    <div className="flex flex-col bg-white">
      <div className="border-b bg-gray-50">
        <div className="flex">
          {TAB_CONFIG.map((tab) => {
            const Icon = tab.icon;
            return (
              <button
                key={tab.id}
                type="button"
                onClick={() => setActiveTab(tab.id)}
                title={tab.tooltip}
                className={`px-3 py-2 border-b-2 ${
                  activeTab === tab.id
                    ? "border-blue-600 text-blue-600"
                    : "border-transparent text-gray-500 hover:text-gray-700"
                }`}
              >
                <Icon className="w-4 h-4" />
              </button>
            );
          })}
        </div>
      </div>

      {activeTab === "basic" && (
        <div className="w-full">
          <div className="space-y-2">
              {/* Model Name - Always Visible WITH LABEL */}
                  <div>
                    <div className="flex items-center gap-1 mb-1">
                      <label className="text-xs font-medium text-gray-700">
                        Model Name
                      </label>
                      <span title="A unique identifier for this simulation model. This name helps you organize and identify different models in your workspace.">
                        <Info className="w-3 h-3 text-gray-400 hover:text-gray-600 cursor-help" />
                      </span>
                    </div>
                    <input
                      type="text"
                      name="name"
                      className="w-full px-2 py-1 text-xs border rounded"
                      value={localModelDraft.name}
                      placeholder="Enter model name"
                      onChange={handleChange}
                      onBlur={saveNow}
                    />
                </div>

                {/* Run Time - Conditional: Only in Clock mode */}
                {localModelDraft.simulationTimeType === SimulationTimeType.Clock && (
                  <div>
                    <div className="flex items-center gap-1 mb-1">
                      <label className="text-xs font-medium text-gray-700">
                        Run Time
                      </label>
                      <span title="The total duration the simulation will run in Clock mode. Specify the time period and unit (e.g., 8 Hours, 30 Days).">
                        <Info className="w-3 h-3 text-gray-400 hover:text-gray-600 cursor-help" />
                      </span>
                    </div>
                    <div className="grid grid-cols-2 gap-1">
                      <input
                        type="number"
                        name="runClockPeriod"
                        className="w-full px-2 py-1 text-xs border rounded"
                        value={localModelDraft.runClockPeriod || 0}
                        onChange={handleChange}
                        min="0"
                        onBlur={saveNow}
                      />
                      <select
                        name="runClockPeriodUnit"
                        className="w-full px-2 py-1 text-xs border rounded bg-white"
                        value={localModelDraft.runClockPeriodUnit || PeriodUnit.HOURS}
                        onChange={handleChange}
                      >
                        {Object.values(PeriodUnit).map((unit) => (
                          <option key={unit} value={unit}>
                            {unit}
                          </option>
                        ))}
                      </select>
                    </div>
                  </div>
                )}

                {/* Advanced Settings - Accordion */}
                <AccordionSection
                  title="Advanced Settings"
                  isExpanded={isAdvancedExpanded}
                  onToggle={() => setIsAdvancedExpanded(!isAdvancedExpanded)}
                >
                  <div className="space-y-2">
                    {/* Replications */}
                    <div>
                      <div className="flex items-center gap-1 mb-1">
                        <label className="text-xs font-medium text-gray-700">
                          Replications
                        </label>
                        <span title="The number of independent simulation runs to perform. Multiple replications help account for randomness and provide statistical confidence in the results.">
                          <Info className="w-3 h-3 text-gray-400 hover:text-gray-600 cursor-help" />
                        </span>
                      </div>
                      <input
                        type="number"
                        name="reps"
                        className="w-full px-2 py-1 text-xs border rounded"
                        value={localModelDraft.reps}
                        onChange={handleChange}
                        min="1"
                        onBlur={saveNow}
                      />
                    </div>

                    {/* Time Mode */}
                    <div>
                      <div className="flex items-center gap-1 mb-1">
                        <label className="text-xs font-medium text-gray-700">
                          Time Mode
                        </label>
                        <span title="Select how time is represented in the simulation. Clock mode uses relative time periods (e.g., Hour 0 to Hour 100), while Calendar Date mode uses actual dates and times.">
                          <Info className="w-3 h-3 text-gray-400 hover:text-gray-600 cursor-help" />
                        </span>
                      </div>
                      <select
                        name="simulationTimeType"
                        className="w-full px-2 py-1 text-xs border rounded bg-white"
                        value={localModelDraft.simulationTimeType}
                        onChange={handleChange}
                      >
                        {Object.values(SimulationTimeType).map((type) => (
                          <option key={type} value={type}>
                            {type}
                          </option>
                        ))}
                      </select>
                    </div>

                    {/* Clock Mode Fields - Conditional */}
                    {localModelDraft.simulationTimeType === SimulationTimeType.Clock && (
                      <>
                        {/* Clock Unit */}
                        <div>
                          <div className="flex items-center gap-1 mb-1">
                            <label className="text-xs font-medium text-gray-700">
                              Clock Unit
                            </label>
                            <span title="The base time unit for the simulation clock (e.g., Minutes, Hours, Days). All time-based values in the model will be expressed in relation to this unit.">
                              <Info className="w-3 h-3 text-gray-400 hover:text-gray-600 cursor-help" />
                            </span>
                          </div>
                          <select
                            name="oneClockUnit"
                            className="w-full px-2 py-1 text-xs border rounded bg-white"
                            value={localModelDraft.oneClockUnit}
                            onChange={handleChange}
                          >
                            {Object.values(PeriodUnit).map((unit) => (
                              <option key={unit} value={unit}>
                                {unit}
                              </option>
                            ))}
                          </select>
                        </div>

                        {/* Warmup Time - Simple number + dropdown */}
                        <div>
                          <div className="flex items-center gap-1 mb-1">
                            <label className="text-xs font-medium text-gray-700">
                              Warmup Time
                            </label>
                            <span title="The initial period during which the simulation reaches steady state. Statistics collected during warmup are discarded to ensure more accurate results.">
                              <Info className="w-3 h-3 text-gray-400 hover:text-gray-600 cursor-help" />
                            </span>
                          </div>
                          <div className="grid grid-cols-2 gap-1">
                            <input
                              type="number"
                              name="warmupClockPeriod"
                              className="w-full px-2 py-1 text-xs border rounded"
                              value={localModelDraft.warmupClockPeriod || 0}
                              onChange={handleChange}
                              min="0"
                              onBlur={saveNow}
                            />
                            <select
                              name="warmupClockPeriodUnit"
                              className="w-full px-2 py-1 text-xs border rounded bg-white"
                              value={localModelDraft.warmupClockPeriodUnit || PeriodUnit.HOURS}
                              onChange={handleChange}
                            >
                              {Object.values(PeriodUnit).map((unit) => (
                                <option key={unit} value={unit}>
                                  {unit}
                                </option>
                              ))}
                            </select>
                          </div>
                        </div>
                      </>
                    )}

                    {/* Calendar Date Mode Fields - Conditional */}
                    {localModelDraft.simulationTimeType === SimulationTimeType.CalendarDate && (
                      <>
                        <div>
                          <div className="flex items-center gap-1 mb-1">
                            <label className="text-xs font-medium text-gray-700">
                              Start Date
                            </label>
                            <span title="The calendar date and time when the simulation begins in Calendar Date mode. Use this to model processes that align with specific real-world dates.">
                              <Info className="w-3 h-3 text-gray-400 hover:text-gray-600 cursor-help" />
                            </span>
                          </div>
                          <input
                            type="datetime-local"
                            name="startDateTime"
                            className="w-full px-2 py-1 text-xs border rounded"
                            value={localModelDraft.startDateTime?.toISOString().slice(0, 16) || ""}
                            onChange={handleChange}
                            onBlur={saveNow}
                          />
                        </div>
                        <div>
                          <div className="flex items-center gap-1 mb-1">
                            <label className="text-xs font-medium text-gray-700">
                              Finish Date
                            </label>
                            <span title="The calendar date and time when the simulation ends in Calendar Date mode. The simulation will run from Start Date to this Finish Date.">
                              <Info className="w-3 h-3 text-gray-400 hover:text-gray-600 cursor-help" />
                            </span>
                          </div>
                          <input
                            type="datetime-local"
                            name="finishDateTime"
                            className="w-full px-2 py-1 text-xs border rounded"
                            value={localModelDraft.finishDateTime?.toISOString().slice(0, 16) || ""}
                            onChange={handleChange}
                            onBlur={saveNow}
                          />
                        </div>
                        <div>
                          <div className="flex items-center gap-1 mb-1">
                            <label className="text-xs font-medium text-gray-700">
                              Warmup Date
                            </label>
                            <span title="The calendar date and time when the warmup period ends and statistics collection begins in Calendar Date mode. Set this between Start Date and Finish Date.">
                              <Info className="w-3 h-3 text-gray-400 hover:text-gray-600 cursor-help" />
                            </span>
                          </div>
                          <input
                            type="datetime-local"
                            name="warmupDateTime"
                            className="w-full px-2 py-1 text-xs border rounded"
                            value={localModelDraft.warmupDateTime?.toISOString().slice(0, 16) || ""}
                            onChange={handleChange}
                            onBlur={saveNow}
                          />
                        </div>
                      </>
                    )}
                  </div>
                </AccordionSection>

                {/* Auto-save status */}
                <SaveStatusLine status={status} lastSavedAt={lastSavedAt} />
              </div>
          </div>
      )}
      {activeTab === "states" && (
        <StatesEditor
            states={states}
            onStatesChange={onStatesChange}
            defaultComponentType="ALL"
          />
      )}
      {activeTab === "requirements" && (
        <ResourceRequirementsManager
            requirements={resourceRequirements || []}
            availableResources={referenceData?.resources || []}
            onAdd={() => {
              setEditingRequirement(null);
              setRequirementModalOpen(true);
            }}
            onEdit={(req) => {
              const structure = convertRootClausesToStructure(req.rootClauses);
              setEditingRequirement({ id: req.id, name: req.name, structure });
              setRequirementModalOpen(true);
            }}
            onDelete={(id) => {
              const remainingRequirements = (resourceRequirements || []).filter(req => req.id !== id);
              const requirementsPayload = prepareRequirementsForStorage(
                remainingRequirements,
                referenceData?.resources || []
              );
              updateResourceRequirements(requirementsPayload);
            }}
            getUsageCount={(id) => {
              // Calculate how many actions use this requirement
              const activities = referenceData?.activities || [];
              let count = 0;
              for (const activity of activities) {
                const reqIds = activity.actionRequirementIds || [];
                count += reqIds.filter(reqId => reqId === id).length;
              }
              return count;
            }}
          />
      )}
      {activeTab === "scenarios" && (
        <ScenariosAndRunsPanel
          documentId={selection.documentContext?.documentId}
          pageId={selection.documentContext?.pageId}
          modelName={localModelDraft.name}
          referenceData={referenceData}
          onScenariosChange={updateScenarioDefinitions}
          onSimulate={onSimulate ?? (() => {})}
        />
      )}
      {activeTab === "validation" && (
        <ValidationDashboard
          validationState={validationState || null}
          referenceData={referenceData}
        />
      )}

      {/* Resource Requirement Modal */}
      <ResourceRequirementModal
        isOpen={requirementModalOpen}
        onClose={() => {
          setRequirementModalOpen(false);
          setEditingRequirement(null);
        }}
        onSave={(data) => {
          const rootClauses = convertStructureToRootClauses(data.structure);

          // Create the updated/new requirement
          let savedRequirement: ResourceRequirement;
          let updatedRequirementsList: ResourceRequirement[];

          if (editingRequirement) {
            // Update existing requirement (could be editing auto or custom)
            savedRequirement = new ResourceRequirement(editingRequirement.id, data.name, rootClauses);
            updatedRequirementsList = (resourceRequirements || []).map(req =>
              req.id === editingRequirement.id ? savedRequirement : req
            );
          } else {
            // Create new requirement (always custom)
            savedRequirement = new ResourceRequirement(`req-${Date.now()}`, data.name, rootClauses);
            updatedRequirementsList = [...(resourceRequirements || []), savedRequirement];
          }

          // IMPORTANT: Only send custom requirements to storage (filter out unmodified auto-requirements)
          // - New requirements (ID starts with "req-") are always custom
          // - Edited requirements (even if ID matches resource) become custom overrides
          // - Unmodified auto-requirements (ID matches resource, wasn't just edited) are filtered out
          const customRequirementsToSave = updatedRequirementsList.filter(req =>
            !isAutoGeneratedRequirement(req, referenceData?.resources || []) || req.id === savedRequirement.id
          );

          // Serialize for storage
          const savePayload = customRequirementsToSave.map(req => ({
            id: req.id,
            name: req.name,
            type: SimulationObjectType.ResourceRequirement,
            rootClauses: req.rootClauses
          }));

          // Send custom-only array to extension
          updateResourceRequirements(savePayload);

          // Close modal
          setRequirementModalOpen(false);
          setEditingRequirement(null);
        }}
        editingRequirement={editingRequirement}
        availableResources={referenceData?.resources || []}
      />
    </div>
  );
};

export default React.memo(ModelEditor);
