import {
  Model,
  PeriodUnit,
  SimulationTimeType,
  SimulationObjectType,
  ResourceRequirement,
} from "@quodsi/shared";

/**
 * Input type for model data - accepts various formats
 */
export type ModelInput = Model | { data: Partial<Model> } | Partial<Model>;

/**
 * Extracts and normalizes model data from props into a clean Model object.
 *
 * This handles multiple data formats:
 * - Full Model objects
 * - Raw data objects with nested .data property
 * - Missing/null values (creates default model with safe defaults)
 * - Initializes all required model properties with appropriate fallbacks
 *
 * @param mod - Model data in various formats
 * @returns Normalized Model object with all properties initialized
 */
export const extractModelData = (mod: ModelInput): Model => {
  const data = (mod as any).data || mod;

  const result = {
    id: data.id || "",
    name: data.name || "New Model",
    type: SimulationObjectType.Model,
    reps: data.reps || 1,
    seed: data.seed || 0,
    simulationTimeType: data.simulationTimeType || SimulationTimeType.Clock,
    oneClockUnit: data.oneClockUnit || PeriodUnit.HOURS,
    warmupClockPeriod: data.warmupClockPeriod || 0,
    warmupClockPeriodUnit: data.warmupClockPeriodUnit || PeriodUnit.HOURS,
    runClockPeriod: data.runClockPeriod || 0,
    runClockPeriodUnit: data.runClockPeriodUnit || PeriodUnit.HOURS,
    warmupDateTime: data.warmupDateTime || null,
    startDateTime: data.startDateTime || null,
    finishDateTime: data.finishDateTime || null,
    description: data.description || "",
  };

  return result;
};

/**
 * Creates a new Model instance with updated values while preserving immutability.
 *
 * This helper ensures that Model updates trigger React re-renders by creating
 * new object references. It handles partial updates, filling in missing values
 * from the base Model.
 *
 * @param base - The base Model to update
 * @param updates - Partial object containing fields to update
 * @returns New Model object with updated values
 *
 * @example
 * const updated = updateModelImmutably(model, { name: "New Model Name", reps: 10 });
 */
export const updateModelImmutably = (
  base: Model,
  updates: Partial<Model>
): Model => {
  return {
    ...base,
    ...updates,
  };
};

/**
 * Checks if a resource requirement is auto-generated by the system.
 *
 * Auto-generated requirements have IDs that match resource IDs - they are
 * created automatically by the extension and should be filtered out before
 * sending custom requirements to storage.
 *
 * @param requirement - The resource requirement to check
 * @param availableResources - List of available resources to compare against
 * @returns true if the requirement is auto-generated, false if it's custom
 */
export const isAutoGeneratedRequirement = (
  requirement: ResourceRequirement,
  availableResources: Array<{ id: string }>
): boolean => {
  return availableResources.some(r => r.id === requirement.id);
};

/**
 * Prepares resource requirements for storage by filtering out auto-generated
 * requirements and serializing to plain objects.
 *
 * This function consolidates the common logic used in both delete and save operations:
 * 1. Filters out auto-generated requirements (ID matches resource ID)
 * 2. Serializes remaining custom requirements to plain objects for storage
 *
 * @param requirements - Array of resource requirements to process
 * @param availableResources - List of available resources for auto-requirement detection
 * @returns Array of serialized custom requirements ready for storage
 *
 * @example
 * const payload = prepareRequirementsForStorage(updatedRequirements, resources);
 * updateResourceRequirements(payload);
 */
export const prepareRequirementsForStorage = (
  requirements: ResourceRequirement[],
  availableResources: Array<{ id: string }>
): Array<{
  id: string;
  name: string;
  type: SimulationObjectType;
  rootClauses: any[];
}> => {
  // Filter out auto-generated requirements
  const customRequirements = requirements.filter(
    req => !isAutoGeneratedRequirement(req, availableResources)
  );

  // Serialize to plain objects
  return customRequirements.map(req => ({
    id: req.id,
    name: req.name,
    type: SimulationObjectType.ResourceRequirement,
    rootClauses: req.rootClauses,
  }));
};
