// A page's Model reaches the panel as RAW storage JSON (itemDataBuilder does
// JSON.parse(JSON.stringify(rawData))), so every calendar-mode date is a
// STRING there, never a Date. ModelEditor then calls
// `localModelDraft.startDateTime.toISOString()` -- a TypeError that blanks
// the whole panel (smoke 2026-09-06, first calendar-mode page generated by
// the Advisor). extractModelData is the one place every model enters the
// editor, so it coerces there, the way the extension's ModelLucid already
// does on its own read path.
import { describe, it, expect } from 'vitest';
import { extractModelData } from '../modelEditorHelpers';
import { SimulationTimeType } from '@quodsi/lucid-shared';

describe('extractModelData stored dates', () => {
  it('coerces ISO-string start/finish/warmup dates from storage into Date objects', () => {
    const model = extractModelData({
      data: {
        id: 'page-1',
        name: 'Clinic',
        timeMode: SimulationTimeType.CalendarDate,
        startDateTime: '2027-01-01T00:00:00.000Z',
        finishDateTime: '2027-01-31T00:00:00.000Z',
        warmupDateTime: '2026-12-31T00:00:00.000Z',
      } as any,
    });
    expect(model.startDateTime).toBeInstanceOf(Date);
    expect(model.startDateTime!.toISOString()).toBe('2027-01-01T00:00:00.000Z');
    expect(model.finishDateTime).toBeInstanceOf(Date);
    expect(model.warmupDateTime).toBeInstanceOf(Date);
  });

  it('keeps Date instances and turns null/undefined/unparseable into null', () => {
    const d = new Date('2027-02-01T00:00:00.000Z');
    const model = extractModelData({
      data: {
        id: 'page-1',
        startDateTime: d,
        finishDateTime: 'not a date',
        warmupDateTime: undefined,
      } as any,
    });
    expect(model.startDateTime).toBe(d);
    expect(model.finishDateTime).toBeNull();
    expect(model.warmupDateTime).toBeNull();
  });
});
